### ISSUE TITLE
Subnets less than /24 are not seen in vRA's network selection.

### ISSUE THREAD

**Issue by atm8119** [isas2/vra-solarwinds-ipam#3]
There is a bug in the code resulting in issues with subnets /23, /22, and /21.

vRA pulls these subnets in and they are visible as part of the payload to vRA, but I think the payload is incorrect. Data validation by vRA cuts these subnets out of the list for Network Profiles.

That calculation for "endIPAddress" seems to be at least in part the cause, where the shortcut of 2^(32 - 24) - 2 works for 24 and larger, but 2^(32 - 21) - 2  results in an invalid IP --->   10.24.40.2046

**Comment by atm8119** [comment]
<img width="984" alt="image (4)" src="https://user-images.githubusercontent.com/16367022/197283068-4735ff70-f5ac-4e3a-9605-c69cb9960479.png">

**Comment by isas2** [comment]
Fixed in https://github.com/isas2/vra-solarwinds-ipam/commit/f8725464ebc32679d3d6cc4bf523da11395c9655
